### PR TITLE
Basic lottie implementation

### PR DESCRIPTION
**Pull request by MaheshNandam**
@akiran ,

please have a look at this PR.

### CODE REVIEW

**Comment by chakrihacker** [comment]
Hey, you have deleted all my work!!

**Comment by MaheshNandam** [comment]
hey @chakrihacker,

Indeed yes!, because the previous repo doesn't have the RN structure, though I had updated with RN structure along with Lottie implementation if you don't mind can you integrate your code to this current repo then everyone can have the single repo for all the topics and easy to generate APK and IPA for attendance to see all our outputs in one file.

**Comment by akiran** [comment]
@MaheshNandam @chakrihacker Everyone can maintain there demos in separate branches.
We needn't merge all demos into single branch.


@MaheshNandam Can you move lottie demos to lottie branch.
you can push your layout animation demos to layout-animations branch

**Comment by akiran** [comment]
@MaheshNandam  @chakrihacker I am closing this PR because we will never merge it.

We will just maintain separate branches

**Comment by chakrihacker** [comment]
Sure then I will make master branch for slides and other branches for their respective demos

**Pull request closed without merging**
